openapi: 3.0.0
info:
  version: 1.0.0
  title: PawPals API
  description: API for the LBAW 2024/2025 project
externalDocs:
  description: Find more info here.
  url: 'https://gitlab.up.pt/lbaw/lbaw2425/lbaw24121'
tags:
  - name: 'M01: Authentication'
  - name: 'M02: Users'
  - name: 'M03: Posts'
  - name: 'M04: Comments'
  - name: 'M05: Groups'
  - name: 'M06: Search'
  - name: 'M07: Admin'
  - name: 'M08: Pictures'
  - name: 'M09: Messages'
  - name: 'M10: Bans'
  - name: 'M11: Appeals'
  - name: 'M12: Notifications'
paths:
  /bans:
    post:
      operationId: R1001
      summary: 'R1001: Create a new ban for a user'
      description: Blocks a user by creating a new ban entry.
      tags:
        - 'M10: Bans'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ID of the user to ban
              required:
                - id
      responses:
        '200':
          description: User successfully blocked.
        '403':
          description: Unauthorized. You do not have permission to perform this action.
  '/bans/{id}':
    get:
      operationId: R1002
      summary: 'R1002: Retrieve all bans for a user'
      description: Fetch all ban records associated with a user by ID.
      tags:
        - 'M10: Bans'
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the user
      responses:
        '200':
          description: Successfully retrieved user bans.
        '403':
          description: Unauthorized. You do not have permission to access this resource.
    delete:
      operationId: R1003
      summary: 'R1003: Delete a specific ban'
      description: Removes a ban for a user by specifying the ban ID.
      tags:
        - 'M10: Bans'
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the ban to delete
      responses:
        '200':
          description: Ban successfully deleted.
        '403':
          description: Unauthorized. You do not have permission to delete this ban.
        '404':
          description: Ban not found. The specified ban ID does not exist.
  /bans/unblock:
    put:
      operationId: R1004
      summary: 'R1004: Unblock a user'
      description: Updates a ban to set it as inactive
      tags:
        - 'M10: Bans'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ID of the user to unblock
              required:
                - id
      responses:
        '200':
          description: User successfully unblocked.
        '403':
          description: Unauthorized. You do not have permission to perform this action.
  /bans/reason:
    put:
      operationId: R1005
      summary: 'R1005: Update ban reason'
      description: Modifies the reason for an existing ban.
      tags:
        - 'M10: Bans'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ID of the ban to update
                reason:
                  type: string
                  description: New reason for the ban
              required:
                - id
                - reason
      responses:
        '200':
          description: Ban reason successfully updated.
        '403':
          description: Unauthorized. You do not have permission to perform this action.
